select first_name ||' ' || last_name as namalengkap, job_id, salary, ((salary*30)*12) as gajisetahun from employees where manager_id = 100
--select last_name, salary, (salary*30) as gajiperbulan, job_id from employees where commission_pct is null
--select first_name ||' '|| last_name as namalengkap, job_id, salary, (salary*12) as gajisetahun from employees where manager_id = 100
--SELECT DISTINCT (department_id) FROM employees ORDER BY department_id ASC
--where salary > 3200.00 AND salary < 12000.00 
--first_name like'_l%'
--first_name like 'A%' --or last_name like 'B%'
--first_name LIKE 'A%' AND last_name LIKE 'B%'
--employee_id NOT IN (101,103,105,107)
--AND salary > 1000
--employee_id in (101,103,105,107)
--salary > 1500 and employee_id > 200
--first_name = 'Daniel'
